[general]
import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[font]
size = 12.0

[font.bold]
family = "Sarasa Term Slab SC"
style = "Bold"

[font.bold_italic]
family = "Sarasa Term Slab SC"
style = "Bold Italic"

[font.italic]
family = "Sarasa Term Slab SC"
style = "Italic"

[font.normal]
family = "Sarasa Term Slab SC"
style = "Regular"
